import { test, expect } from '@playwright/test';

test('Administrador', async ({ page }) => {
  await page.goto('http://localhost:4200/');
  await page.waitForTimeout(500);
  await page.getByText('Registrarse').click();
  await page.waitForTimeout(500);
  await page.getByLabel('Administrador').check();
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe clave de administrador').click();
  await page.getByPlaceholder('Escribe clave de administrador').fill('109');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe clave de administrador').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('R');
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('Randy');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe nombre').press('Tab');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('H');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('Hernandez');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe correo electrónico').click();
  await page.getByPlaceholder('Escribe correo electrónico').fill('randy@gmail.com');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe correo electrónico').press('Tab');
  await page.getByPlaceholder('Escribe contraseña').fill('123456789');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe contraseña').press('Tab');
  await page.getByPlaceholder('Confirma la contraseña').fill('123456789');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe teléfono').click();
  await page.getByPlaceholder('Escribe teléfono').fill('294918343');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe RFC').click();
  await page.getByPlaceholder('Escribe RFC').press('CapsLock');
  await page.getByPlaceholder('Escribe RFC').fill('KAIJMEILOP12');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe la edad').click();
  await page.getByPlaceholder('Escribe la edad').fill('20');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe la ocupación').click();
  await page.getByPlaceholder('Escribe la ocupación').fill('A');
  await page.getByPlaceholder('Escribe la ocupación').press('CapsLock');
  await page.getByPlaceholder('Escribe la ocupación').fill('');
  await page.getByPlaceholder('Escribe la ocupación').press('CapsLock');
  await page.getByPlaceholder('Escribe la ocupación').fill('P');
  await page.getByPlaceholder('Escribe la ocupación').press('CapsLock');
  await page.getByPlaceholder('Escribe la ocupación').fill('Programador');
  await page.waitForTimeout(500);
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });

  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.waitForTimeout(500);
  await page.goto('http://localhost:4200/');
  await page.getByText('Registrarse').click();
  await page.waitForTimeout(500);
  await page.getByLabel('Alumno').check();
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe ID o matrícula').click();
  await page.getByPlaceholder('Escribe ID o matrícula').press('CapsLock');
  await page.getByPlaceholder('Escribe ID o matrícula').fill('202150641');
  await page.getByPlaceholder('Escribe ID o matrícula').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('J');
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('Jared');
  await page.getByPlaceholder('Escribe nombre').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('M');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('Muñoz');
  await page.getByText('Correo electrónico').click();
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe correo electrónico').fill('amunozbaez669@gmail.com');
  await page.getByPlaceholder('Escribe correo electrónico').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe contraseña').fill('123456');
  await page.getByPlaceholder('Escribe contraseña').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Confirma la contraseña').fill('123456');
  await page.waitForTimeout(500);
  await page.getByLabel('Open calendar').click();
  await page.getByLabel('Choose month and year').click();
  await page.getByLabel('Choose date').click();
  await page.waitForTimeout(500);
  await page.getByLabel('March 19,').click();
  await page.waitForTimeout(500);
  await page.getByLabel('Open calendar').click();
  await page.waitForTimeout(500);
  await page.getByRole('dialog', { name: 'Fecha de nacimiento' }).locator('div').nth(1).click();
  await page.getByLabel('Choose month and year').click();
  await page.getByLabel('Previous 24 years').click();
  await page.getByLabel('2003').click();
  await page.getByLabel('September').click();
  await page.getByLabel('September 22,').click();
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe CURP').click();
  await page.getByPlaceholder('Escribe CURP').fill('dkmjuioplkmnswerti');
  await page.getByPlaceholder('Escribe CURP').press('Tab');
  await page.getByPlaceholder('Escribe RFC').fill('sikmjrujn123');
  await page.waitForTimeout(500);
  await page.locator('mat-form-field:nth-child(11) > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click();
  await page.getByPlaceholder('Escribe edad').fill('20');
  await page.locator('mat-form-field:nth-child(12) > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click();
  await page.waitForTimeout(500);
  await page.getByLabel('Teléfono').fill('2721564025');
  await page.getByLabel('Ocupación').click();
  await page.getByLabel('Ocupación').press('CapsLock');
  await page.waitForTimeout(500);
  await page.getByLabel('Ocupación').press('CapsLock');
  await page.getByLabel('Ocupación').fill('e');
  await page.getByLabel('Ocupación').press('CapsLock');
  await page.getByLabel('Ocupación').fill('E');
  await page.getByLabel('Ocupación').press('CapsLock');
  await page.waitForTimeout(500);
  await page.getByLabel('Ocupación').fill('Estudiante');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });

  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.waitForTimeout(500);
  await page.goto('http://localhost:4200/');
  await page.waitForTimeout(500);
  await page.getByText('Registrarse').click();
  await page.waitForTimeout(500);
  await page.getByLabel('Maestro').check();
  await page.getByPlaceholder('Escribe ID de trabajador').click();
  await page.getByPlaceholder('Escribe ID de trabajador').press('CapsLock');
  await page.getByPlaceholder('Escribe ID de trabajador').fill('2984391');
  await page.getByPlaceholder('Escribe ID de trabajador').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe nombre').fill('L');
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('Luis ');
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('Luis Y');
  await page.getByPlaceholder('Escribe nombre').press('CapsLock');
  await page.getByPlaceholder('Escribe nombre').fill('Luis Yael');
  await page.getByPlaceholder('Escribe nombre').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe apellidos').fill('m');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('M');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('Mendez ');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('Mendez S');
  await page.getByPlaceholder('Escribe apellidos').press('CapsLock');
  await page.getByPlaceholder('Escribe apellidos').fill('Mendez Sanchez');
  await page.getByPlaceholder('Escribe apellidos').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe correo electrónico').fill('luis@gmail.com');
  await page.getByPlaceholder('Escribe correo electrónico').press('Tab');
  await page.getByPlaceholder('Escribe contraseña').fill('123456');
  await page.getByPlaceholder('Escribe contraseña').press('Tab');
  await page.getByPlaceholder('Confirma la contraseña').fill('123456');
  await page.waitForTimeout(500);
  await page.getByText('Fecha de nacimiento').click();
  await page.getByLabel('Choose month and year').click();
  await page.getByLabel('Previous 24 years').click();
  await page.getByLabel('1996').click();
  await page.getByLabel('February').click();
  await page.getByLabel('February 6,').click();
  await page.waitForTimeout(500);
  await page.locator('mat-form-field:nth-child(9) > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click();
  await page.getByPlaceholder('Escribe teléfono').press('CapsLock');
  await page.getByPlaceholder('Escribe teléfono').fill('983491323');
  await page.waitForTimeout(500);
  await page.locator('mat-form-field:nth-child(10) > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click();
  await page.getByPlaceholder('Escribe RFC').fill('AKIOLPEFGIOI');
  await page.getByPlaceholder('Escribe RFC').press('Tab');
  await page.waitForTimeout(500);
  await page.getByPlaceholder('Escribe el cubículo').fill('301');
  await page.getByPlaceholder('Escribe el cubículo').press('Tab');
  await page.waitForTimeout(500);
  await page.getByText('Área de investigación').click();
  await page.getByRole('option', { name: 'Desarrollo Web' }).click();
  await page.waitForTimeout(500);
  await page.getByLabel('Tecnologías Web').check();
  await page.getByLabel('Administración de S.O.').check();
  await page.waitForTimeout(500);
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.goto('http://localhost:4200/');
  await page.waitForTimeout(1000);
});